mirror_to_github:
  script:
    - git config --global http.postBuffer 157286400
    - git clone --mirror $CI_REPOSITORY_URL
    - cd $(basename $CI_REPOSITORY_URL)
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/xelmedia/kameleon-assistant-plugin-zip.git
    - git config --unset http.postBuffer
    - git push --force github refs/heads/*:refs/heads/*
    - git push --force github refs/tags/*:refs/tags/*
  only:
    - master
    - tags