variables:
  GITHUB_REPO: "xelmedia/kameleon-assistant-plugin-zip"
  PLUGIN_NAME: "zilch-assistant"

stages:
  - mirror
  - release

mirror_to_github:
  stage: mirror
  script:
    - git config --global http.postBuffer 157286400
    - git clone --mirror $CI_REPOSITORY_URL ./repo-mirror
    - cd ./repo-mirror
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/xelmedia/kameleon-assistant-plugin-zip.git
    - git push --force github refs/heads/*:refs/heads/*
    - git push --force github refs/tags/*:refs/tags/*
  only:
    - master
    - tags

github_release:
  stage: release
  image: alpine:latest
  script:
    - apk add --no-cache curl jq
    
    - |
      GITHUB_API="https://api.github.com/repos/${GITHUB_REPO}"
      
      # Create release
      RELEASE_RESPONSE=$(curl -X POST \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Accept: application/vnd.github.v3+json" \
        ${GITHUB_API}/releases \
        -d "{
          \"tag_name\": \"${CI_COMMIT_TAG}\",
          \"name\": \"Release ${CI_COMMIT_TAG}\",
          \"body\": \"Release ${CI_COMMIT_TAG}\",
          \"draft\": false,
          \"prerelease\": false
        }")
      
      RELEASE_ID=$(echo $RELEASE_RESPONSE | jq -r .id)
      
      curl -X POST \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Content-Type: application/zip" \
        -H "Accept: application/vnd.github.v3+json" \
        --data-binary @${PLUGIN_NAME}.zip \
        "${GITHUB_API}/releases/${RELEASE_ID}/assets?name=${PLUGIN_NAME}.zip"
  only:
    - tags
